### ISSUE TITLE
文档里的小错误

### ISSUE THREAD

**Issue by Adsicmes** [st1020/alicebot#1]
https://docs.alicebot.dev/guide/plugin-advanced.html
第三行 block 写错了

很喜欢这个框架，简单易用，开发者加油！

**Comment by st1020** [comment]
已修复，谢谢

**Comment by Adsicmes** [comment]
https://docs.alicebot.dev/guide/builtin-message.html

消息类块中第一个和第二个代码块中的`msg`写成了`mas`
`mas_seg.type = 'text'`

<img width="338" alt="image" src="https://user-images.githubusercontent.com/79645438/179647556-c3f88b43-4081-4ea6-94e1-e348f3b62ef8.png">
