### ISSUE TITLE
请问怎么发送多张图片

### ISSUE THREAD

**Issue by coferry** [st1020/alicebot#10]
我在文档中似乎没找到发送图片的方法，示例里也没看见，所以想请教一下，我很喜欢这个框架，谢谢

**Comment by Adsicmes** [comment]
`message += CQHttpMessage.image(image)`

需要具体到适配器的消息类

**Comment by st1020** [comment]
可以参考文档中的：
https://docs.alicebot.dev/guide/builtin-message.html#示例
如果你使用的是 CQHTTP 协议的话，还可以参考 OneBot v11 标准的图片消息段格式的 file 参数：
https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#图片
