### ISSUE TITLE
有没有交流群

### ISSUE THREAD

**Issue by coferry** [st1020/alicebot#11]
如题。
顺便说一个我目前遇到的问题：就是在制作自定义合并转发的时候似乎出了点问题，但是我不知道错在了哪里，有没有例子参考一下
![7Y(AL71%U`LSOEX}5)3HJY](https://user-images.githubusercontent.com/86643414/201521338-bdcfe4ab-5e2d-4fb6-8857-bcbef6876502.png)

![E`L4 PGI8$5V7D10R_GM2F1](https://user-images.githubusercontent.com/86643414/201521331-34f9515a-9705-4956-8005-269eda1f2189.png)

**Comment by coferry** [comment]
![image](https://user-images.githubusercontent.com/86643414/201522074-e50c5ef0-e516-4f65-8d8d-4cca924821f1.png)
报错是这样

**Comment by st1020** [comment]
目前还没有，过两天我建一个 :)

**Comment by coferry** [comment]
> 目前还没有，过两天我建一个 :)

好的，建完后记得发群号在这个issue

**Comment by st1020** [comment]
已经建好了：674802046

**Comment by Admsec** [comment]
> 674802046

好的，已经加群了，坐等同意
