### ISSUE TITLE
同一个插件内定义两个类会导致启动时不导入包

### ISSUE THREAD

**Issue by Admsec** [st1020/alicebot#12]
这里我定义了两个类（类名没有重复）
![image](https://user-images.githubusercontent.com/86643414/201607277-74e2c94e-30fe-4861-a30f-b3830c5f23c5.png)
下面显示不导入包了
![image](https://user-images.githubusercontent.com/86643414/201607322-648866e1-6ac3-4747-928f-e89e2093d5e4.png)
下面是正常的样子
![image](https://user-images.githubusercontent.com/86643414/201607488-e0e7468a-726f-4b82-99db-752bfee83e13.png)

**Comment by Adsicmes** [comment]
正常建议是一个文件内只定义一个Plugin的子类(

**Comment by coferry** [comment]
> 正常建议是一个文件内只定义一个Plugin的子类(

Emmmmm......没有别的办法了吗，这是两个比较相似的功能，我想放在一个插件内，或者同一个目录内

**Comment by Adsicmes** [comment]
可以放在同一目录内   或者整合在一起(当然不建议这么干)

放在同一目录里单独导入就行了 或者你等等  看开发者怎么说

**Comment by coferry** [comment]
> 可以放在同一目录内 或者整合在一起(当然不建议这么干)
> 
> 放在同一目录里单独导入就行了 或者你等等 看开发者怎么说

好的谢谢你，我看看作者怎么说先

**Comment by st1020** [comment]
目前还不允许在一个 Python 模块中定义多个插件，这主要是因为目前 [插件配置](https://docs.alicebot.dev/guide/plugin-advanced.html#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE) 会检测 Python 模块中的 Config 类作为插件的配置类，如果允许在一个 Python 模块中定义多个插件，则会无法区分配置类是用于哪个插件的。此外，还会影响到插件的 [热重载](https://docs.alicebot.dev/guide/hot-reload.html) 功能。但是，我目前打算在未来的版本更改插件配置的加载方式，目前的设计还不够好，这将会是一个 breaking change，将会解除对此的限制。

**Comment by st1020** [comment]
请保持此 issue 开启以追踪此问题。

**Comment by coferry** [comment]
> 目前还不允许在一个 Python 模块中定义多个插件，这主要是因为目前 [插件配置](https://docs.alicebot.dev/guide/plugin-advanced.html#%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE) 会检测 Python 模块中的 Config 类作为插件的配置类，如果允许在一个 Python 模块中定义多个插件，则会无法区分配置类是用于哪个插件的。此外，还会影响到插件的 [热重载](https://docs.alicebot.dev/guide/hot-reload.html) 功能。但是，我目前打算在未来的版本更改插件配置的加载方式，目前的设计还不够好，这将会是一个 breaking change，将会解除对此的限制。

好的明白了！谢谢作者，这个机器人说实话我还挺喜欢的，让我感受到了写插件的乐趣hhhh : )

**Comment by st1020** [comment]
已经在 commit https://github.com/st1020/alicebot/commit/759216a856caed514ee221ec474c18467d826e00 中修改此行为，并在 v0.6.0 以上版本生效
