### ISSUE TITLE
使用mirai http方式无法返回消息

### ISSUE THREAD

**Issue by mlzboy** [st1020/alicebot#17]
![2022-12-16_23-04-46](https://user-images.githubusercontent.com/42778/208127904-4fae103d-febf-4633-a4d6-3198b71c64d5.png)
你好，我在尝试mirai http的方式进行使用这个框架，我在爬虫这个测试用例时，发现我发了消息，没有回应，不知道是哪里的问题

**Comment by mlzboy** [comment]
我使用pip安装的alicebot包

**Comment by st1020** [comment]
根据你的截图，Mirai 成功连接了 AliceBot，AliceBot 也接收到消息，但是却并没有交由图中所示的插件处理，请检查是否成功导入了插件，如果成功导入了插件会在日志中打印类似：“Succeeded to load plugin "HalloAlice" from class "<class 'hello_mirai.HalloAlice'>"”

下图是正常情况下的截图：

![4C8F9CDD-617E-4216-BA5F-A8CC2310BA6C](https://user-images.githubusercontent.com/47559019/208388776-dd940cd1-c2d9-46a9-b987-cecb2541e61a.png)
