### ISSUE TITLE
添加bot退出时插件一次性执行的函数

### ISSUE THREAD

**Issue by Adsicmes** [st1020/alicebot#19]
我某个插件用了持久性的数据库连接，想要在退出bot时断开连接，但目前我通过bot_exit_hook的同步钩子函数做不到异步关闭连接

**Comment by st1020** [comment]
已经在 https://github.com/st1020/alicebot/commit/8490a0fdc5930864c44252f184de41004f2f5107 修改，现在 bot_exit_hook 钩子函数要求为异步函数
