### ISSUE TITLE
对消息段的组织发生错误

### ISSUE THREAD

**Issue by Adsicmes** [st1020/alicebot#2]
## 以下为源代码
<img width="421" alt="image" src="https://user-images.githubusercontent.com/79645438/179648039-351938aa-d2c2-439c-b2b9-56fb1d376b32.png">

## 以下为标错行报错信息
`2022-07-19 09:59:21.824 | ERROR    | alicebot:_handle_event:283 - Exception in plugin "<freegame.FreeGame object at 0x00000161236DACE0>": TypeError("MessageSegment.__init__() missing 1 required positional argument: 'type'")
`

## 以下为文档内容
<img width="562" alt="image" src="https://user-images.githubusercontent.com/79645438/179648366-dbad556a-3122-4f97-8180-2e9278b84765.png">
来自 https://docs.alicebot.dev/guide/builtin-message.html

## 问题
1.经实际使用发现不符
2.缺少富文本特性支持

**Comment by st1020** [comment]
这里的文档不是这个意思，内置消息类是一个抽象基类（abstract base class），文档中的代码只是一个例子，这里的文档不是很清晰，我之后改一下。

还有确实不支持文本中内嵌CQ码，因为AliceBot对此进行了封装，通过消息和消息段来实现富文本。

这里是使用CQHTTP适配器的发送富文本的例子：

```python
from alicebot.plugin import Plugin
from alicebot.adapter.cqhttp.event import MessageEvent
from alicebot.adapter.cqhttp.message import CQHTTPMessage, CQHTTPMessageSegment


class Test(Plugin[MessageEvent, None]):  # 这里的泛型参数参考插件进阶篇的插件类的泛型支持
    async def handle(self) -> None:
        msg = CQHTTPMessage()
        for i in ["a", "b", "c"]:
            msg += CQHTTPMessageSegment.text(i)
            msg += CQHTTPMessageSegment.image("file:///path/temp.png")
        await self.event.reply(msg)

    async def rule(self) -> bool:
        if self.event.adapter.name != "cqhttp":
            return False
        if self.event.type != "message":
            return False
        return True

```

**Comment by Adsicmes** [comment]
那么那个`MessageSegment`类实际上有什么用途呢

**Comment by Adsicmes** [comment]
作为抽象类给其他具体的消息段类进行继承吗

**Comment by st1020** [comment]
是的，它是提供给适配器开发者继承用的基类，不应该直接实例化，应该使用适配器提供的Message和MessageSegment

**Comment by Adsicmes** [comment]
好的，了解
