### ISSUE TITLE
MiraiMessage 富文本组合时出现错误

### ISSUE THREAD

**Issue by BiDuang** [st1020/alicebot#22]
尝试让
```python3
MiraiMessageSegment.at(self.event.sender.id) + MiraiMessageSegment.plain("ABC")
```
组合时，出现如下错误：
```python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~\site-packages\alicebot\message.py", line 379, in __add__
    return self._message_class(self) + other
TypeError: _message_class() takes 1 positional argument but 2 were given
```
环境为 
- Windows 10 Home Edition 22H2 19045.2604 with Windows Feature Experience Pack 120.2212.4190.0
- Python 3.9.5 64bit

谢谢！

**Comment by st1020** [comment]
已经在 commit https://github.com/st1020/alicebot/commit/f5df7bafa792779efd56e5d6ca335385e406a999 中修复

**Comment by BiDuang** [comment]
阁下可以为此项目设置一个工作流自动更新 `PyPi` 吗？这样也便于观察构建结果。

**Comment by st1020** [comment]
> 阁下可以为此项目设置一个工作流自动更新 `PyPi` 吗？这样也便于观察构建结果。

是指对于每一次 commit 都 release 到 PyPi 吗？这样会 release 太多吧，并且如何决定 release 的版本号也是个问题，目前我没有在其他项目中看到类似的操作

**Comment by BiDuang** [comment]
> > 阁下可以为此项目设置一个工作流自动更新 `PyPi` 吗？这样也便于观察构建结果。
> 
> 是指对于每一次 commit 都 release 到 PyPi 吗？这样会 release 太多吧，并且如何决定 release 的版本号也是个问题，目前我没有在其他项目中看到类似的操作

您可以单独指定 Actions 运行的触发器，参阅 [触发器事件](https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows)

例如，您可以单独开设一个分支作为Release版本分支，然后每次需要更新 PyPi 包时向此分支推送，即会自动构建。

希望能帮助到您。

**Comment by st1020** [comment]
> > > 阁下可以为此项目设置一个工作流自动更新 `PyPi` 吗？这样也便于观察构建结果。
> > 
> > 
> > 是指对于每一次 commit 都 release 到 PyPi 吗？这样会 release 太多吧，并且如何决定 release 的版本号也是个问题，目前我没有在其他项目中看到类似的操作
> 
> 您可以单独指定 Actions 运行的触发器，参阅 [触发器事件](https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows)
> 
> 例如，您可以单独开设一个分支作为Release版本分支，然后每次需要更新 PyPi 包时向此分支推送，即会自动构建。
> 
> 希望能帮助到您。

谢谢，了解了，会添加类似功能的 workflow 的
