### ISSUE TITLE
[Feature] 添加重载函数

### ISSUE THREAD

**Issue by Adsicmes** [st1020/alicebot#3]
为插件添加`self.bot.reload()`重载函数，可以热重载，也可以整个重启

---

有一种设想，可以实施，但是少了这个函数无法**便捷地**实施，具体如下:

>1.开发机的文件系统分两部分，一部分为开发项目，一部分为生产环境用的项目文件
>2.生产环境用项目文件与服务器端开发环境项目文件使用rsync进行绑定
>3.在本地开发完毕后，将新的插件文件或更改的文件放入开发机的生产环境项目文件中使用rsync进行同步

好处也就只有方便懒人了，而且做一个重载，应该不会非常难，实现退出函数再重新运行bot.run()即可，但我不了解alicebot的代码结构，没办法帮忙，请求加入这个功能

**Comment by st1020** [comment]
很好的建议！这个功能会添加的，但有一些细节问题需要考虑，所以可能会在晚些添加。
除此之外我认为还可以提供一个类似 uvicorn 的可选的自动热更新，参考：https://www.uvicorn.org/settings/#reloading-without-watchfiles

**Comment by st1020** [comment]
已经添加 reload_plugins 方法：https://github.com/st1020/alicebot/commit/4eb1634ae812ba0ec92261d600bd0814f708aff0
自动热更新功能将在之后添加。

**Comment by st1020** [comment]
已经发布 0.5.0 版本，添加重新加载相关功能，并且更新了文档，请参考：https://docs.alicebot.dev/guide/hot-reload.html
