### ISSUE TITLE
[Feature] 添加详细报错

### ISSUE THREAD

**Issue by Adsicmes** [st1020/alicebot#4]
在写插件的过程中难免出错，而alicebot的报错机制过于笼统，希望添加更完美的报错

至少在`alicebot\__init__.py`的283与287行添加更详细的报错

loguru中有集成一个better_exceptions的库，可以更加详细地输出方法报错的所有信息，只需要将logger.error()改为logger.exception()即可

**Comment by Adsicmes** [comment]
如果觉得这样的报错过于冗长，还可以使用python原版报错
在导入traceback包的前提下在上述行后添加`logger.error(f"\n{traceback.format_exc()}")`即可

**Comment by st1020** [comment]
感谢建议，已添加功能：https://github.com/st1020/alicebot/commit/1565f42a755f8e9cb173f5760070f5864bca1f3e
