### ISSUE TITLE
[BugFix] cqhttp适配器的消息事件使用str()不会自动转义字符

### ISSUE THREAD

**Issue by Adsicmes** [st1020/alicebot#5]
如题
建议在
https://github.com/st1020/alicebot/blob/ed1700ee0e58cc0877cf98343fbd11307fa8d25f/packages/alicebot-adapter-cqhttp/alicebot/adapter/cqhttp/message.py#L31

31行所在的方法中添加类似于
```python
string.replace('&amp;', '&').replace('&#91;', '[').replace('&#93;',']').replace('&#44;', ',')  
```
的字段，虽然难看，但确实有用

**Comment by st1020** [comment]
根据[OneBot v11文档](https://github.com/botuniverse/onebot-11/blob/master/message/array.md#%E6%B6%88%E6%81%AF%E6%AE%B5%E6%95%B0%E7%BB%84)，在使用“数组格式”时不需要进行转义。
如果你在使用时发现需要转义，可能是你所使用的协议端程序没有遵循OneBot v11标准，请向那个协议端程序反馈。
