### ISSUE TITLE
更新后错误

### ISSUE THREAD

**Issue by Adsicmes** [st1020/alicebot#6]
2022-08-21 23:03:22.697 | ERROR    | alicebot.log:error_or_exception:15 - Config dict parse error: ValidationError(model='MainConfig', errors=[{'loc': ('plugins',), 'msg': 'none is not an allowed value', 'type': 'type_error.none.not_allowed'}])

以上为报错
以下为config.json

```json
{
    "plugins": null,
    "plugin_dir": [
        "plugins",
        "plugins/osu"
    ],
    "adapters": ["alicebot.adapter.cqhttp"],
    "cqhttp": {
        "host": "127.0.0.1",
        "port": 9999,
        "url": "/cqhttp/ws",
        "api_timeout": 10000
    },
    "superuser": [1483492332],
    "osu": {
        "api":{
            "v2": {
                "id": 6322,
                "secret": "G5Dpfd1hAgAt8zkt0aFklV8bteaZITv1vC2bxcfO"
            }
        }
    }
}
```

**Comment by Adsicmes** [comment]
![image](https://user-images.githubusercontent.com/79645438/185873062-567fda13-d62f-4f15-b5e4-1a094ac88441.png)
已经卸载所有环境包并重装到最新版本 报错如上图
![image](https://user-images.githubusercontent.com/79645438/185874013-b7a39dab-d7e0-4aae-9759-4e8e06a00327.png)
main.py
<img width="764" alt="image" src="https://user-images.githubusercontent.com/79645438/185874194-4963673e-be3e-4d62-99fb-353211028884.png">
config.json

**Comment by st1020** [comment]
抱歉，这里确实是版本更新后忘记列出的不兼容更改，修复方式非常简单，只需要修改 `"plugins": null,` 为 `"plugins": [],` ，或者直接删除此行即可

**Comment by Adsicmes** [comment]
记得更改文档
