### ISSUE TITLE
关于pypi

### ISSUE THREAD

**Issue by Adsicmes** [st1020/alicebot#9]
pypi那里是自动更新吗，还是说手动更新

我`pip install alicebot[all] --upgrade`的时候，一直是环境满足，怀疑自己没更新上

**Comment by st1020** [comment]
你可以通过 `pip show alicebot` 显示目前安装的 AliceBot 版本，截至目前 AliceBot 的最新版本是 0.5.0 (2022-08-21)。
自2022-08-21之后的 commit 还没有被发布到 pipy。

**Comment by st1020** [comment]
0.5.1 版本已经于 PyPi 发布。
